server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/postgres
    username: postgres
    password:
  cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static: us-east-1

sqs:
  notifications:
    queue:
      name: mDiscovery-sqs.fifo
      region: us-east-1
